CREATE DATABASE IF NOT EXISTS target365 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE target365;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  username VARCHAR(80) NOT NULL UNIQUE,
  email VARCHAR(120) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(60) NOT NULL DEFAULT 'Pengguna',
  avatar_url VARCHAR(255) NOT NULL,
  tagline VARCHAR(255) NOT NULL DEFAULT '',
  about TEXT NOT NULL,
  birthday VARCHAR(40) NOT NULL DEFAULT '',
  gender VARCHAR(20) NOT NULL DEFAULT '',
  phone VARCHAR(40) NOT NULL DEFAULT '',
  location VARCHAR(120) NOT NULL DEFAULT '',
  language VARCHAR(40) NOT NULL DEFAULT 'Bahasa Indonesia',
  date_format VARCHAR(20) NOT NULL DEFAULT 'DD/MM/YYYY',
  dark_mode TINYINT(1) NOT NULL DEFAULT 0,
  compact_view TINYINT(1) NOT NULL DEFAULT 0,
  two_factor TINYINT(1) NOT NULL DEFAULT 0,
  notif_push TINYINT(1) NOT NULL DEFAULT 1,
  notif_email TINYINT(1) NOT NULL DEFAULT 0,
  notif_target_reminder TINYINT(1) NOT NULL DEFAULT 1,
  notif_achievement TINYINT(1) NOT NULL DEFAULT 1,
  notif_weekly TINYINT(1) NOT NULL DEFAULT 0,
  notif_motivasi TINYINT(1) NOT NULL DEFAULT 1,
  reminder_time VARCHAR(10) NOT NULL DEFAULT '07:00',
  dnd_start VARCHAR(10) NOT NULL DEFAULT '22:00',
  dnd_end VARCHAR(10) NOT NULL DEFAULT '06:00',
  calendar_month_label VARCHAR(40) NOT NULL DEFAULT 'Mei 2025',
  calendar_month TINYINT UNSIGNED NOT NULL DEFAULT 5,
  calendar_year SMALLINT UNSIGNED NOT NULL DEFAULT 2025,
  calendar_selected_day TINYINT UNSIGNED NOT NULL DEFAULT 21,
  notifications_count INT UNSIGNED NOT NULL DEFAULT 3
);

CREATE TABLE IF NOT EXISTS target_categories (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  name VARCHAR(120) NOT NULL,
  description TEXT NOT NULL,
  icon_name VARCHAR(60) NOT NULL,
  icon_bg VARCHAR(16) NOT NULL,
  icon_color VARCHAR(16) NOT NULL,
  jumlah_target VARCHAR(30) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'Aktif',
  sort_order INT NOT NULL DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS targets (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  title VARCHAR(180) NOT NULL,
  icon_name VARCHAR(60) NOT NULL,
  icon_bg VARCHAR(16) NOT NULL,
  icon_color VARCHAR(16) NOT NULL,
  category VARCHAR(120) NOT NULL,
  category_color VARCHAR(16) NOT NULL,
  priority VARCHAR(20) NOT NULL,
  deadline VARCHAR(40) NOT NULL,
  progress DECIMAL(5,2) NOT NULL DEFAULT 0,
  progress_label VARCHAR(20) NOT NULL,
  status VARCHAR(40) NOT NULL,
  status_color VARCHAR(16) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dashboard_motivations (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  title VARCHAR(120) NOT NULL,
  quote TEXT NOT NULL,
  author VARCHAR(120) NOT NULL DEFAULT 'Target365',
  is_today TINYINT(1) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dashboard_quotes (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  category VARCHAR(80) NOT NULL,
  category_color VARCHAR(16) NOT NULL,
  quote TEXT NOT NULL,
  date_label VARCHAR(40) NOT NULL,
  liked TINYINT(1) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS calendar_events (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  day TINYINT UNSIGNED NOT NULL,
  title VARCHAR(180) NOT NULL,
  color VARCHAR(16) NOT NULL,
  time_label VARCHAR(40) NOT NULL DEFAULT '',
  event_type VARCHAR(40) NOT NULL DEFAULT 'Target',
  sort_order INT NOT NULL DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS deadlines (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  color VARCHAR(16) NOT NULL,
  title VARCHAR(180) NOT NULL,
  date_label VARCHAR(40) NOT NULL,
  remaining VARCHAR(40) NOT NULL,
  due_date DATE NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS report_category_progress (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  name VARCHAR(120) NOT NULL,
  color VARCHAR(16) NOT NULL,
  percent INT NOT NULL,
  target_summary VARCHAR(80) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS report_trends (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  label VARCHAR(40) NOT NULL,
  value INT NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS profile_activities (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  icon_name VARCHAR(60) NOT NULL,
  color VARCHAR(16) NOT NULL,
  background_color VARCHAR(16) NOT NULL,
  title VARCHAR(180) NOT NULL,
  description TEXT NOT NULL,
  time_label VARCHAR(40) NOT NULL,
  created_at DATETIME NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS profile_achievements (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  icon_name VARCHAR(60) NOT NULL,
  color VARCHAR(16) NOT NULL,
  background_color VARCHAR(16) NOT NULL,
  title VARCHAR(180) NOT NULL,
  subtitle VARCHAR(255) NOT NULL,
  date_label VARCHAR(40) NOT NULL,
  achieved_at DATETIME NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS profile_sessions (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  icon_name VARCHAR(60) NOT NULL,
  title VARCHAR(180) NOT NULL,
  location VARCHAR(120) NOT NULL,
  current_device TINYINT(1) NOT NULL DEFAULT 0,
  last_active DATETIME NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

